# Generated by Django 6.0.1 on 2026-01-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speeches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speech',
            name='created_at',
        ),
        migrations.AddField(
            model_name='speech',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='speeches/'),
        ),
    ]
