# Generated by Django 6.0.1 on 2026-01-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speeches', '0002_remove_speech_created_at_speech_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='add_later',
            field=models.BooleanField(default=False),
        ),
    ]
